questions = {

    "Chemistry": [
{"question":"Which quantum number determines size of orbital?","options":["n","l","m","s"],"answer":"n"},
{"question":"Which quantum number determines shape?","options":["n","l","m","s"],"answer":"l"},
{"question":"pH of 0.001M HCl?","options":["1","2","3","4"],"answer":"3"},
{"question":"Strongest acid?","options":["HF","HCl","HBr","HI"],"answer":"HI"},
{"question":"Hybridization of NH3?","options":["sp","sp2","sp3","sp3d"],"answer":"sp3"},
{"question":"Bond angle in CH4?","options":["90","104.5","109.5","120"],"answer":"109.5"},
{"question":"Oxidation state of S in H2SO4?","options":["+2","+4","+6","-2"],"answer":"+6"},
{"question":"Molar mass of H2SO4?","options":["96","98","100","102"],"answer":"98"},
{"question":"Which gas is ideal?","options":["H2","He","O2","CO2"],"answer":"He"},
{"question":"Avogadro number?","options":["6.022e23","3.14e23","9.8e23","1.6e19"],"answer":"6.022e23"},
{"question":"Unit of molarity?","options":["mol/kg","mol/L","g/L","kg/mol"],"answer":"mol/L"},
{"question":"Which is amphoteric?","options":["NaOH","Al(OH)3","HCl","NH3"],"answer":"Al(OH)3"},
{"question":"Bond order of N2?","options":["1","2","3","2.5"],"answer":"3"},
{"question":"Which has highest boiling point?","options":["H2O","H2S","H2Se","H2Te"],"answer":"H2O"},
{"question":"Which is reducing agent?","options":["O2","H2","Cl2","F2"],"answer":"H2"},
{"question":"pH of neutral solution?","options":["5","6","7","8"],"answer":"7"},
{"question":"Which metal is liquid?","options":["Na","Hg","Fe","Cu"],"answer":"Hg"},
{"question":"Which is strongest base?","options":["NaOH","KOH","NH3","CaOH"],"answer":"KOH"},
{"question":"CO2 shape?","options":["Linear","Bent","Trigonal","Tetrahedral"],"answer":"Linear"},
{"question":"Hybridization in CO2?","options":["sp","sp2","sp3","dsp2"],"answer":"sp"},
{"question":"Which is polar?","options":["CO2","CH4","NH3","BF3"],"answer":"NH3"},
{"question":"Which is nonpolar?","options":["H2O","NH3","CO2","SO2"],"answer":"CO2"},
{"question":"Unit of pressure?","options":["Pa","J","W","N"],"answer":"Pa"},
{"question":"Boyle’s law?","options":["P∝1/V","P∝V","V∝T","P∝T"],"answer":"P∝1/V"},
{"question":"Charles law?","options":["V∝T","P∝1/V","P∝T","V∝1/T"],"answer":"V∝T"},
{"question":"Which acid in vinegar?","options":["Citric","Acetic","Lactic","Formic"],"answer":"Acetic"},
{"question":"Atomic number of Na?","options":["10","11","12","13"],"answer":"11"},
{"question":"Which gas in photosynthesis?","options":["CO2","O2","H2","N2"],"answer":"O2"},
{"question":"Oxidation state O in H2O?","options":["-2","-1","+1","+2"],"answer":"-2"},
{"question":"Type of bond in NaCl?","options":["Ionic","Covalent","Metallic","Hydrogen"],"answer":"Ionic"},
{"question":"Molar mass CO2?","options":["28","32","44","56"],"answer":"44"},
{"question":"Which isotope used in dating?","options":["C12","C13","C14","C11"],"answer":"C14"},
{"question":"Combustion is?","options":["Endo","Exo","Neutral","Decomp"],"answer":"Exo"},
{"question":"Which has max EN?","options":["O","Cl","F","N"],"answer":"F"},
{"question":"Which gas evolved Zn+HCl?","options":["O2","H2","N2","CO2"],"answer":"H2"},
{"question":"Valency of carbon?","options":["2","3","4","6"],"answer":"4"},
{"question":"Which is alkali metal?","options":["Na","Ca","Al","Fe"],"answer":"Na"},
{"question":"Which is noble gas?","options":["O2","N2","Ne","H2"],"answer":"Ne"},
{"question":"Which is acid?","options":["NaOH","HCl","NH3","KOH"],"answer":"HCl"},
{"question":"Which is base?","options":["HCl","NaOH","CO2","SO2"],"answer":"NaOH"},
{"question":"Which is salt?","options":["NaCl","HCl","NaOH","NH3"],"answer":"NaCl"},
{"question":"Which is oxide?","options":["CO2","HCl","NaCl","NH3"],"answer":"CO2"},
{"question":"Which is organic?","options":["CH4","NaCl","H2O","CO2"],"answer":"CH4"},
{"question":"Which is inorganic?","options":["NaCl","C2H6","CH4","C6H6"],"answer":"NaCl"},
{"question":"Which is aromatic?","options":["Benzene","Ethane","Methane","Propane"],"answer":"Benzene"},
{"question":"Which is saturated?","options":["Ethane","Ethene","Ethyne","Benzene"],"answer":"Ethane"},
{"question":"Which is unsaturated?","options":["Ethene","Methane","Ethane","Propane"],"answer":"Ethene"},
{"question":"Which is alkane?","options":["CH4","C2H4","C2H2","C6H6"],"answer":"CH4"},
{"question":"Which is alkene?","options":["C2H4","CH4","C2H6","C3H8"],"answer":"C2H4"},
{"question":"Which is alkyne?","options":["C2H2","CH4","C2H6","C3H8"],"answer":"C2H2"}
],

    "Physics": [
{"question":"Unit of force?","options":["N","J","W","Pa"],"answer":"N"},
{"question":"F=ma belongs to?","options":["Newton 1","Newton 2","Newton 3","None"],"answer":"Newton 2"},
{"question":"Unit of work?","options":["J","W","N","Pa"],"answer":"J"},
{"question":"Unit of power?","options":["W","J","N","Pa"],"answer":"W"},
{"question":"Speed formula?","options":["d/t","t/d","d*t","d+t"],"answer":"d/t"},
{"question":"Unit of velocity?","options":["m/s","m","s","m/s2"],"answer":"m/s"},
{"question":"Acceleration unit?","options":["m/s2","m/s","m","s"],"answer":"m/s2"},
{"question":"g value?","options":["9.8","10","8.9","7"],"answer":"9.8"},
{"question":"Work in circular motion?","options":["0","1","-1","∞"],"answer":"0"},
{"question":"Unit of energy?","options":["J","W","N","Pa"],"answer":"J"},
{"question":"Unit of momentum?","options":["kgm/s","N","J","W"],"answer":"kgm/s"},
{"question":"Light speed?","options":["3e8","3e6","3e5","3e7"],"answer":"3e8"},
{"question":"Unit of frequency?","options":["Hz","m/s","J","N"],"answer":"Hz"},
{"question":"Time period?","options":["1/f","f","f2","1/f2"],"answer":"1/f"},
{"question":"Wave type sound?","options":["Longitudinal","Transverse","EM","None"],"answer":"Longitudinal"},
{"question":"Unit electric current?","options":["Amp","Volt","Ohm","Watt"],"answer":"Amp"},
{"question":"Unit voltage?","options":["Volt","Amp","Ohm","Watt"],"answer":"Volt"},
{"question":"Ohm law?","options":["V=IR","P=VI","F=ma","E=mc2"],"answer":"V=IR"},
{"question":"Resistance unit?","options":["Ohm","Volt","Amp","Watt"],"answer":"Ohm"},
{"question":"Capacitance unit?","options":["Farad","Henry","Tesla","Weber"],"answer":"Farad"},
{"question":"Magnetic flux unit?","options":["Weber","Tesla","Henry","Amp"],"answer":"Weber"},
{"question":"Lens formula?","options":["1/f","f","f2","1/f2"],"answer":"1/f"},
{"question":"Mirror type convex?","options":["Diverging","Converging","Plane","None"],"answer":"Diverging"},
{"question":"Mirror concave?","options":["Converging","Diverging","Plane","None"],"answer":"Converging"},
{"question":"Unit pressure?","options":["Pa","J","N","W"],"answer":"Pa"},
{"question":"Density formula?","options":["m/v","v/m","mv","m+v"],"answer":"m/v"},
{"question":"SI unit density?","options":["kg/m3","g/cm3","kg","m"],"answer":"kg/m3"},
{"question":"Heat unit?","options":["J","W","N","Pa"],"answer":"J"},
{"question":"Thermometer measures?","options":["Temp","Pressure","Force","Work"],"answer":"Temp"},
{"question":"Unit temp?","options":["K","C","F","J"],"answer":"K"},
{"question":"AC frequency India?","options":["50","60","40","30"],"answer":"50"},
{"question":"Unit inductance?","options":["Henry","Farad","Tesla","Weber"],"answer":"Henry"},
{"question":"Transformer works on?","options":["Induction","Refraction","Reflection","Conduction"],"answer":"Induction"},
{"question":"EM wave speed?","options":["3e8","3e6","3e5","3e7"],"answer":"3e8"},
{"question":"Which wave no medium?","options":["Light","Sound","Water","Air"],"answer":"Light"},
{"question":"Unit charge?","options":["Coulomb","Volt","Amp","Ohm"],"answer":"Coulomb"},
{"question":"Electron charge?","options":["1.6e-19","1.6e19","3e8","9.8"],"answer":"1.6e-19"},
{"question":"Gravitational constant?","options":["6.67e-11","9.8","3e8","1.6e-19"],"answer":"6.67e-11"},
{"question":"Energy formula?","options":["mc2","ma","mv","mgh"],"answer":"mc2"},
{"question":"Potential energy?","options":["mgh","mv","mc2","ma"],"answer":"mgh"},
{"question":"Kinetic energy?","options":["1/2mv2","mv","mgh","mc2"],"answer":"1/2mv2"},
{"question":"Momentum formula?","options":["mv","ma","mgh","mc2"],"answer":"mv"},
{"question":"Hooke law?","options":["F=kx","F=ma","V=IR","P=VI"],"answer":"F=kx"},
{"question":"Unit torque?","options":["Nm","J","W","Pa"],"answer":"Nm"},
{"question":"Angular velocity?","options":["rad/s","m/s","m","s"],"answer":"rad/s"},
{"question":"Unit power?","options":["W","J","N","Pa"],"answer":"W"},
{"question":"Work formula?","options":["Fd","mv","ma","mgh"],"answer":"Fd"},
{"question":"Electric field unit?","options":["N/C","J","W","Pa"],"answer":"N/C"},
{"question":"Magnetic field unit?","options":["Tesla","Weber","Henry","Amp"],"answer":"Tesla"},
{"question":"Resistors series?","options":["Add","Divide","Multiply","Subtract"],"answer":"Add"}
],

    "Mathematics": [
{"question":"Derivative x^2?","options":["2x","x","x2","1"],"answer":"2x"},
{"question":"Integral 1/x?","options":["lnx","x","1/x","x2"],"answer":"lnx"},
{"question":"sin2+cos2?","options":["1","0","2","x"],"answer":"1"},
{"question":"tan45?","options":["1","0","-1","∞"],"answer":"1"},
{"question":"cos90?","options":["0","1","-1","∞"],"answer":"0"},
{"question":"Limit sinx/x?","options":["1","0","∞","-1"],"answer":"1"},
{"question":"log1?","options":["0","1","-1","∞"],"answer":"0"},
{"question":"log10?","options":["1","0","10","-1"],"answer":"1"},
{"question":"Slope formula?","options":["(y2-y1)/(x2-x1)","x/y","y/x","none"],"answer":"(y2-y1)/(x2-x1)"},
{"question":"Distance formula?","options":["√((x2-x1)^2+(y2-y1)^2)","x+y","x-y","xy"],"answer":"√((x2-x1)^2+(y2-y1)^2)"},
{"question":"Probability range?","options":["0-1","1-2","-1-1","0-∞"],"answer":"0-1"},
{"question":"Det identity?","options":["1","0","-1","n"],"answer":"1"},
{"question":"sin30?","options":["1/2","1","0","√3"],"answer":"1/2"},
{"question":"cos60?","options":["1/2","1","0","√3"],"answer":"1/2"},
{"question":"tan0?","options":["0","1","-1","∞"],"answer":"0"},
{"question":"sec0?","options":["1","0","∞","-1"],"answer":"1"},
{"question":"cosec90?","options":["1","0","∞","-1"],"answer":"1"},
{"question":"cot45?","options":["1","0","∞","-1"],"answer":"1"},
{"question":"Matrix order?","options":["rows x cols","cols x rows","sum","product"],"answer":"rows x cols"},
{"question":"Transpose?","options":["Rows↔Cols","Add","Multiply","Subtract"],"answer":"Rows↔Cols"},
{"question":"Mean formula?","options":["Σx/n","n/x","x/n","none"],"answer":"Σx/n"},
{"question":"Median?","options":["Middle","Avg","Max","Min"],"answer":"Middle"},
{"question":"Mode?","options":["Most freq","Least","Avg","Sum"],"answer":"Most freq"},
{"question":"Quadratic formula?","options":["(-b±√(b2-4ac))/2a","ax+b","x2","none"],"answer":"(-b±√(b2-4ac))/2a"},
{"question":"Roots nature D>0?","options":["Real","Imag","Equal","None"],"answer":"Real"},
{"question":"D=0?","options":["Equal","Real","Imag","None"],"answer":"Equal"},
{"question":"D<0?","options":["Imag","Real","Equal","None"],"answer":"Imag"},
{"question":"sinAcosB identity?","options":["(sin(A+B)+sin(A-B))/2","cos","tan","none"],"answer":"(sin(A+B)+sin(A-B))/2"},
{"question":"Permutation formula?","options":["nPr","nCr","n!","none"],"answer":"nPr"},
{"question":"Combination formula?","options":["nCr","nPr","n!","none"],"answer":"nCr"},
{"question":"n!?","options":["n(n-1)...1","n","1","0"],"answer":"n(n-1)...1"},
{"question":"Vector magnitude?","options":["√(x2+y2)","x+y","xy","x-y"],"answer":"√(x2+y2)"},
{"question":"Unit circle radius?","options":["1","0","∞","2"],"answer":"1"},
{"question":"sin90?","options":["1","0","-1","∞"],"answer":"1"},
{"question":"cos0?","options":["1","0","-1","∞"],"answer":"1"},
{"question":"tan90?","options":["∞","0","1","-1"],"answer":"∞"},
{"question":"Derivative sinx?","options":["cosx","sinx","-cosx","-sinx"],"answer":"cosx"},
{"question":"Derivative cosx?","options":["-sinx","cosx","sinx","-cosx"],"answer":"-sinx"},
{"question":"Integral cosx?","options":["sinx","cosx","-sinx","-cosx"],"answer":"sinx"},
{"question":"Integral sinx?","options":["-cosx","cosx","sinx","-sinx"],"answer":"-cosx"},
{"question":"Equation line?","options":["y=mx+c","x+y","xy","none"],"answer":"y=mx+c"},
{"question":"Circle equation?","options":["x2+y2=r2","x+y=r","xy=r","none"],"answer":"x2+y2=r2"},
{"question":"Ellipse?","options":["x2/a2+y2/b2=1","x+y","xy","none"],"answer":"x2/a2+y2/b2=1"},
{"question":"Hyperbola?","options":["x2/a2-y2/b2=1","x+y","xy","none"],"answer":"x2/a2-y2/b2=1"},
{"question":"Binomial theorem?","options":["(a+b)^n","a+b","ab","none"],"answer":"(a+b)^n"},
{"question":"Sum GP?","options":["a(1-rn)/(1-r)","a+nr","an","none"],"answer":"a(1-rn)/(1-r)"},
{"question":"Sum AP?","options":["n/2(2a+(n-1)d)","a+nr","an","none"],"answer":"n/2(2a+(n-1)d)"},
{"question":"Differentiability implies?","options":["Continuity","Discontinuity","None","Both"],"answer":"Continuity"}
]
}